services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner       # use the production "runner" stage
    image: landing
    container_name: landing
    restart: unless-stopped
    ports:
      - "3005:3000"  

